apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-logger-rolebinding
subjects:
- kind: ServiceAccount
  name: pod-logger-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-logger-role
  apiGroup: rbac.authorization.k8s.io
