apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-logger-rolebinding
  namespace: default # Change this to your desired namespace
subjects:
  - kind: ServiceAccount
    name: pod-logger-sa
    namespace: default # Change this to your desired namespace
roleRef:
  kind: Role
  name: pod-logger-role
  apiGroup: rbac.authorization.k8s.io
